# values.yaml — default values
# Override karo: helm install -f values-prod.yaml
# Ya: helm install --set aws.region=eu-west-1

replicaCount: 1

image:
  # ECR Pull-Through Cache URLs — Docker Hub mirror via VPC endpoint
  # No NAT Gateway needed — nodes pull from ECR (ecr.dkr VPC endpoint)
  # amazon/aws-cli → docker-hub/amazon/aws-cli (namespaced image)
  # nginx → docker-hub/library/nginx (official image = library/ prefix)
  # Override on deploy: --set image.init=<account-id>.dkr.ecr.<region>.amazonaws.com/docker-hub/amazon/aws-cli:latest
  init: "ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/docker-hub/amazon/aws-cli:latest"
  nginx: "ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/docker-hub/library/nginx:alpine"

aws:
  region: us-east-1

serviceAccount:
  name: s3-reader-sa   # Pod Identity Association isse match karta hai (iac/envs/dev/main.tf)

service:
  port: 80

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

gateway:
  create: true           # false karo agar Gateway already exist karta hai
  name: traefik-gateway
  namespace: traefik

route:
  path: /
