apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3-lister.labels" . | nindent 4 }}
  # Pod Identity — NO annotation needed
  # IRSA mein ye hoti: eks.amazonaws.com/role-arn: arn:aws:iam::...
  # Pod Identity association AWS side pe hai (iac/envs/dev/main.tf)
