apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-lab-eks
  region: us-east-1
  version: "1.33"
  tags:
    project: devops-lab

# Reuse existing VPC from Day 4 (free — VPC doesn't cost money)
vpc:
  id: vpc-0b3ef75987ebd61cf
  subnets:
    private:
      us-east-1a:
        id: subnet-09d8c3b1f7ef7c079
      us-east-1b:
        id: subnet-0da15a099f010105f

# privateCluster = eksctl automatically creates ALL required VPC endpoints
# No NAT Gateway needed — eksctl handles: ecr.api, ecr.dkr, eks, ec2, sts, s3, eks-auth
privateCluster:
  enabled: true
  additionalEndpointServices:
    - "sts"
    - "eks-auth"

# OIDC = needed for IRSA (even if using Pod Identity — good to have)
iam:
  withOIDCIssuer: true

managedNodeGroups:
  - name: devops-lab-node-group
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    privateNetworking: true    # nodes sirf private subnets mein
    amiFamily: AmazonLinux2023
    volumeSize: 20
    disableIMDSv1: true        # security best practice — IMDSv2 only
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

addons:
  - name: vpc-cni
    version: latest
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: aws-node
        wellKnownPolicies:
          autoScaler: false
          awsLoadBalancerController: false
          certManager: false
          ebsCSIController: false
          externalDNS: false

  - name: kube-proxy
    version: latest

  - name: coredns
    version: latest

  - name: aws-ebs-csi-driver
    version: latest
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: ebs-csi-controller-sa
        wellKnownPolicies:
          ebsCSIController: true

  - name: eks-pod-identity-agent
    version: latest

  - name: metrics-server
    version: latest
