apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-lab-eks
  region: us-east-1
  version: "1.33"
  tags:
    project: devops-lab

# eksctl creates full VPC — public + private subnets, IGW, route tables
# No hardcoded IDs — works fresh on any AWS account
availabilityZones:
  - us-east-1a
  - us-east-1b

# privateCluster = eksctl creates ALL required VPC endpoints automatically
# Covers: ecr.api, ecr.dkr, eks, ec2, sts, s3, cloudformation, autoscaling
# additionalEndpointServices = eks-auth needed for Pod Identity Agent
privateCluster:
  enabled: true
  additionalEndpointServices:
    - "sts"
    - "eks-auth"

iam:
  withOIDCIssuer: true

managedNodeGroups:
  - name: devops-lab-node-group
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    privateNetworking: true
    amiFamily: AmazonLinux2023
    volumeSize: 20
    disableIMDSv1: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

addons:
  - name: vpc-cni
    version: latest
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: aws-node
        wellKnownPolicies:
          autoScaler: false
          awsLoadBalancerController: false
          certManager: false
          ebsCSIController: false
          externalDNS: false

  - name: kube-proxy
    version: latest

  - name: coredns
    version: latest

  - name: aws-ebs-csi-driver
    version: latest
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: ebs-csi-controller-sa
        wellKnownPolicies:
          ebsCSIController: true

  - name: eks-pod-identity-agent
    version: latest

  - name: metrics-server
    version: latest
