apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-reader-sa
  namespace: default
  # Pod Identity use kar rahe hain — NO annotation needed
  # IRSA mein annotation chahiye thi:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::123:role/...
  # Pod Identity mein AWS side pe association hoti hai — K8s object clean rehta hai
